spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 54570271712-f59ukatoig739fk0evvibotcktb5hlrf.apps.googleusercontent.com
            client-secret : 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
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            #authorization-grant-type: authorization_code
          naver:
            client-id: aRtsZ5tiPboW41G3a8iO
            client-secret: UKEFaAtLbo
            scope: name, email
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          naver:
            issuer-uri: https://nid.naver.com
