spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 54570271712-a2ct0tbftq1gdrnf7p9pk6m8kfs4sbsl.apps.googleusercontent.com
            scope: openid, profile, email
            redirect-uri: "com.mypet:/oauth2redirect/google"
          naver:
            client-id: aRtsZ5tiPboW41G3a8iO
            client-secret: UKEFaAtLbo
            scope: name, email
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          google:
            issuer-uri: https://accounts.google.com
          naver:
            issuer-uri: https://nid.naver.com



