spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 54570271712-6cj9qpfet066g5f0tb8le4hlvovr9073.apps.googleusercontent.com
            client-secret : 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
            scope: openid, profile, email
            redirect-uri: "https://{baseHost}{basePort}/login/oauth2/code/google"
            #authorization-grant-type: authorization_code
          naver:
            client-id: aRtsZ5tiPboW41G3a8iO
            client-secret: UKEFaAtLbo
            scope: name, email
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          naver:
            issuer-uri: https://nid.naver.com
