spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          naver:
            client-id: YOUR_NAVER_CLIENT_ID
            client-secret: YOUR_NAVER_CLIENT_SECRET
            scope: name, email
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          google:
            issuer-uri: https://accounts.google.com
          naver:
            issuer-uri: https://nid.naver.com
